server:
  port: 8084

spring:
  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

jwt:
  algorithm:
    key: ${KEY}

  issuer: ${ISSUER}

  expiration:
    time: ${TIME}
