server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
