server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
